version: 0.2

env:
  variables:
      WORKSPACE_REGION_URL: "https://dbc-6ce36555-d03b.cloud.databricks.com"
      TOKEN: "dapi0030b6cdc004526d839c4f0a3254f5fb"
	  CLUSTER_ID: "0714-065200-rj797bi3"
	  ORG_ID: "3673249481178269"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
       python: 3.8
    commands:
       - pip3 install pytest requests setuptools wheel
       - pip3 install -U databricks-connect--6.4
	   - apt-get update
       - apt-get -y install openjdk-8-jdk
       - update-java-alternatives -s java-1.8.0-openjdk-amd64
       - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/bin
  pre_build:
    commands:
       - echo "y $(WORKSPACE_REGION_URL) $(TOKEN) $(CLUSTER_ID) $(ORG_ID) 15001" | databricks-connect configure
  build:
    commands:
       - databricks-connect test
      # - command
  #post_build:
    #commands:
      # - command
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
